# Generated by Django 4.0 on 2021-12-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_brand_slug_alter_color_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRA LARGE'), ('XXL', 'EXTRA EXTRA LARGE')], max_length=5)),
                ('Tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.tshirt')),
            ],
        ),
    ]
