# Generated by Django 4.0 on 2021-12-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_order_payment_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_address',
            new_name='shipping_address',
        ),
    ]
